# Generated by Django 5.0.1 on 2024-06-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
